Submit Assignments
quanghoang33/Gen-7 pull request #10
Opened 2023-02-23 16:14 UTC by codeeMadness

Hi thay Quang,

There are still one quiz left (quiz 6 - quite tough!), I'm still working on it.
At quiz 2, I do not feel satisfied for my solution, so I will look for more better one.
In the meanwhile, please kindly help to review some other assignments I have resolved.

Regards,
Hang Nguyen

2023-02-25 12:35 UTC, quanghoang33 requested changes

2023-02-25 12:35 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_2/2.k-closest-points-to-origin.py
> +        heapq.heapify(heap)
O(n)

2023-02-25 12:35 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_2/2.k-closest-points-to-origin.py
> +        while k > 0:
O(klogn)

2023-02-25 12:35 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_2/2.k-closest-points-to-origin.py
> +        for index, distance in dict.items():
O(nxk)

2023-02-25 12:35 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_2/2.k-closest-points-to-origin.py
> +        for index, distance in dict.items():
QSelect: O(n) average

2023-02-25 12:35 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_2/2.k-closest-points-to-origin.py
> +        while k > 0:
{dist, index}

2023-02-27 15:19 UTC, codeeMadness commented
Hi thay @quanghoang33 
Please kindly help to review my assignment again.
Thanks,
Hang Nguyen

2023-03-04 11:20 UTC, quanghoang33 commented
lgtm

2023-03-04 11:20 UTC, merged