Submit Lesson 5
quanghoang33/Gen-7 pull request #15
Opened 2023-03-06 01:45 UTC by codeeMadness

Hi thay @quanghoang33,

Please kindly help to review my assignments.

Regards,
Hang Nguyen

2023-03-07 03:11 UTC, quanghoang33 requested changes

2023-03-07 03:11 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_5/insert-delete-getrandom-o1.py
> +    def getRandom(self) -> int:
can you make it O(1) ?

2023-03-07 03:11 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_5/summary-about-ACID.md
> +<h3>ACID stands for:</h3>
this is a good start. I suggest add more detail, recommend watching this video https://youtu.be/5ZjhNTM8XU8 if you don't like reading text book DDIA

2023-03-07 12:50 UTC, quanghoang33 requested changes

2023-03-07 12:50 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_5/insert-delete-getrandom-o1.py
> +    def insert(self, val: int) -> bool:
O(1)

2023-03-07 12:50 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_5/insert-delete-getrandom-o1.py
> +    def remove(self, val: int) -> bool:
O(1)

2023-03-12 15:19 UTC, codeeMadness commented
Hi thay @quanghoang33 ,

Please kindly help to review my updates for assignment again.

Many thanks,
Hang Nguyen

2023-03-13 14:49 UTC, quanghoang33 commented on Homework/Hang_Nguyen/lesson_5/summary-about-ACID.md
> +*A transaction is a way for an application to group several reads and writes together into a logical unit.*
can you give real-world examples for each bullet point? the most important point of a theory question is giving example

2023-03-21 04:58 UTC, merged