Lesson 01: Add solutions for problems 1 and 2.
quanghoang33/Gen-7 pull request #3
Opened 2023-02-13 17:55 UTC by trongle

2023-02-17 14:11 UTC, quanghoang33 requested changes

2023-02-17 14:11 UTC, quanghoang33 commented on Homework/Le_Trong/src/lesson_01/single_number.rs
> + * kề nhau.
maybe use English next time

2023-02-17 14:11 UTC, quanghoang33 commented on Homework/Le_Trong/src/lesson_01/range_sum_query_2d_immutable.rs
> +    pub fn sum_region(&self, row1: i32, col1: i32, row2: i32, col2: i32) -> i32 {
can make it O(1) for sum_region ?

2023-02-18 08:02 UTC, trongle commented on Homework/Le_Trong/src/lesson_01/range_sum_query_2d_immutable.rs
> +    pub fn sum_region(&self, row1: i32, col1: i32, row2: i32, col2: i32) -> i32 {
Sure, let me try.

2023-02-24 14:12 UTC, merged