do home work
quanghoang33/Gen-7 pull request #6
Opened 2023-02-18 08:02 UTC by TruongTD1112

2023-02-18 12:24 UTC, quanghoang33 requested changes

2023-02-18 12:24 UTC, quanghoang33 commented on Homework/Truong_Tran/lesson_1/Subsets.java
> +        int n = (int) Math.pow(2, size);
2^n = 1 << n

2023-02-18 12:24 UTC, quanghoang33 commented on Homework/Truong_Tran/lesson_1/Subsets.java
> +                    Integer.toBinaryString(x)).replaceAll(" ", "0");
O(logn)

2023-02-20 05:34 UTC, TruongTD1112 commented on Homework/Truong_Tran/lesson_1/Subsets.java
> +        int n = (int) Math.pow(2, size);
I understand and I updated

2023-02-20 05:35 UTC, TruongTD1112 commented on Homework/Truong_Tran/lesson_1/Subsets.java
> +                    Integer.toBinaryString(x)).replaceAll(" ", "0");
Yeah, I use built in method in Java to convert decimal number -> binary number

2023-02-27 09:50 UTC, merged